### ISSUE TITLE
Provide a user interface for adding new widget

### ISSUE THREAD

**Issue by mohayemin** [mohayemin/ng-dash#1]
## Tasks  
- [ ] Add an `add widget` button on widget container
- [ ] When `add widget`  is clicked, show a list of registered widgets
- [ ] When a widget is clicked, the widget will be added as the first item of the container.

## Optional Tasks  
- [ ] The users can choose to add the widget at the top or at the bottom of the container
- [ ] The user can choose to insert the widget at a custom index
