### ISSUE TITLE
Provide an user interface to choose a layout for a dashboard

### ISSUE THREAD

**Issue by mohayemin** [mohayemin/ng-dash#2]
## Tasks
- [ ] Give a `change layout` button at the top of the dashboard.
- [ ] When the `change layout` button is clicked, show a list of registered layouts
- [ ] When a layout name is selected, change the layout of the dashboard to that layout
- [ ] When switching a layout, some widgets may not have a container in the new layout. Therefore, each layout must have a default container where all unmapped widgets will be added.
